scrape_configs:
  - job_name: cf_exporter
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:18080']
        labels:
          group: 'cf'
